# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{schedular}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Macario Ortega"]
  s.date = %q{2010-06-29}
  s.description = %q{Bare Bones Events CMS Rails Engine}
  s.email = %q{macarui@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/views/schedular/events/_form.html.erb",
     "app/views/schedular/events/edit.html.erb",
     "app/views/schedular/events/index.html.erb",
     "app/views/schedular/events/new.html.erb",
     "app/views/schedular/events/show.html.erb",
     "config/routes.rb",
     "generators/schedular_migrations/schedular_migrations_generator.rb",
     "generators/schedular_migrations/templates/schedular_migrations.rb",
     "generators/schedular_views/schedular_views_generator.rb",
     "lib/schedular.rb",
     "lib/schedular/event.rb",
     "lib/schedular/events_controller.rb",
     "lib/schedular/time.rb",
     "rails/init.rb",
     "schedular.gemspec",
     "test/helper.rb",
     "test/rails_app/README",
     "test/rails_app/Rakefile",
     "test/rails_app/app/controllers/application_controller.rb",
     "test/rails_app/app/helpers/application_helper.rb",
     "test/rails_app/config/boot.rb",
     "test/rails_app/config/database.yml",
     "test/rails_app/config/environment.rb",
     "test/rails_app/config/environments/development.rb",
     "test/rails_app/config/environments/production.rb",
     "test/rails_app/config/environments/test.rb",
     "test/rails_app/config/initializers/backtrace_silencers.rb",
     "test/rails_app/config/initializers/inflections.rb",
     "test/rails_app/config/initializers/mime_types.rb",
     "test/rails_app/config/initializers/new_rails_defaults.rb",
     "test/rails_app/config/initializers/session_store.rb",
     "test/rails_app/config/locales/en.yml",
     "test/rails_app/config/routes.rb",
     "test/rails_app/db/development.sqlite3",
     "test/rails_app/db/seeds.rb",
     "test/rails_app/doc/README_FOR_APP",
     "test/rails_app/log/development.log",
     "test/rails_app/log/production.log",
     "test/rails_app/log/server.log",
     "test/rails_app/log/test.log",
     "test/rails_app/public/404.html",
     "test/rails_app/public/422.html",
     "test/rails_app/public/500.html",
     "test/rails_app/public/favicon.ico",
     "test/rails_app/public/images/rails.png",
     "test/rails_app/public/index.html",
     "test/rails_app/public/javascripts/application.js",
     "test/rails_app/public/javascripts/controls.js",
     "test/rails_app/public/javascripts/dragdrop.js",
     "test/rails_app/public/javascripts/effects.js",
     "test/rails_app/public/javascripts/prototype.js",
     "test/rails_app/public/robots.txt",
     "test/rails_app/script/about",
     "test/rails_app/script/console",
     "test/rails_app/script/dbconsole",
     "test/rails_app/script/destroy",
     "test/rails_app/script/generate",
     "test/rails_app/script/performance/benchmarker",
     "test/rails_app/script/performance/profiler",
     "test/rails_app/script/plugin",
     "test/rails_app/script/runner",
     "test/rails_app/script/server",
     "test/rails_app/test/performance/browsing_test.rb",
     "test/rails_app/test/test_helper.rb",
     "test/rails_app/tmp/restart.txt",
     "test/support/migrations.rb",
     "test/test_event.rb",
     "test/test_events_controller.rb",
     "test/test_time.rb"
  ]
  s.homepage = %q{http://github.com/maca/schedular}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Bare Bones Events CMS Rails Engine}
  s.test_files = [
    "test/helper.rb",
     "test/rails_app/app/controllers/application_controller.rb",
     "test/rails_app/app/helpers/application_helper.rb",
     "test/rails_app/config/boot.rb",
     "test/rails_app/config/environment.rb",
     "test/rails_app/config/environments/development.rb",
     "test/rails_app/config/environments/production.rb",
     "test/rails_app/config/environments/test.rb",
     "test/rails_app/config/initializers/backtrace_silencers.rb",
     "test/rails_app/config/initializers/inflections.rb",
     "test/rails_app/config/initializers/mime_types.rb",
     "test/rails_app/config/initializers/new_rails_defaults.rb",
     "test/rails_app/config/initializers/session_store.rb",
     "test/rails_app/config/routes.rb",
     "test/rails_app/db/seeds.rb",
     "test/rails_app/test/performance/browsing_test.rb",
     "test/rails_app/test/test_helper.rb",
     "test/support/migrations.rb",
     "test/test_event.rb",
     "test/test_events_controller.rb",
     "test/test_time.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<table_builder>, ["= 0.1.0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<table_builder>, ["= 0.1.0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<table_builder>, ["= 0.1.0"])
  end
end

